version: 1
disable_existing_loggers: False
formatters:
  simple:
    format: "%(asctime)s - %(filename)s - [line:%(lineno)d] - %(levelname)s : %(message)s"
  upgrade:
    format: "%(asctime)s - %(filename)s - %(funcName)s [line:%(lineno)d] - %(levelname)s - %(message)s"

handlers:
  console:
    class: logging.StreamHandler
    level: ERROR
    formatter: simple
    stream: ext://sys.stdout

#  info_file_handler:
#    class: logging.handlers.RotatingFileHandler
#    level: INFO
#    formatter: simple
#    filename: ../logs/info.log
#    maxBytes: 10485760
#    backupCount: 50
#    encoding: utf8
  info_file_handler:
    class: logging.handlers.TimedRotatingFileHandler
    level: INFO
    formatter: simple
    filename: ../logs/auto-test.log
    when: D
    interval: 1
    backupCount: 10
    encoding: utf8
#error_file_handler:
#    class: logging.handlers.RotatingFileHandler
#    level: ERROR
#    formatter: simple
#    filename: ../logs/error.logs
#    maxBytes: 10485760 # 10MB
#    backupCount: 24
#    encoding: utf8

root:
  level: INFO
  handlers: [console, info_file_handler]

#
# loggers:
#     auto-test:
#         level: DEBUG
#         handlers: [info_file_handler]
#         propagate: true

